### ISSUE TITLE
Recent SASS version breaks build

### ISSUE THREAD

**Issue by silend** [Putaitu/putaitu-cms#337]
In `package.json` SASS is required with version `^1.16.0`.

**Doing a fresh clone and installing dependencies with `npm i` will install the current version `1.26.3` which breaks the webpack build.**

Running `npm start` or `npm run start:docker` will throw an error:

```
➜  hashbrown-cms git:(stable) ✗ npm run start:docker

> hashbrown-cms@1.3.7 start:docker /home/silend/code/dne/hashbrown-cms
> npm run build:frontend && cd ./docker && sudo docker-compose up --build -d


> hashbrown-cms@1.3.7 build:frontend /home/silend/code/dne/hashbrown-cms
> webpack --progress

/home/silend/code/dne/hashbrown-cms/node_modules/webpack-cli/bin/cli.js:231
                                throw err;
                                ^

TypeError: Sass.run_ is not a function
    at compileCss (/home/silend/code/dne/hashbrown-cms/webpack.config.js:74:10)
    at Object.<anonymous> (/home/silend/code/dne/hashbrown-cms/webpack.config.js:99:1)
    at Module._compile (/home/silend/code/dne/hashbrown-cms/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
```

Downgrading with `npm i sass@1.16.0` makes above commands work again.

It seems like that there were breaking changes within SASS between version `1.16.0` and `1.26.3`.

**Comment by silend** [comment]
Momentarly locking the version inside `package.json` could be a quick fix for new installs:

```
"sass": "1.16.0",
```

**Comment by silend** [comment]
*Update:* I can confirm it is still working with `sass@1.25.0` and it breaks with `sass@1.26.0`.

In the changelog _potential_ breaking changes are mentioned:
https://github.com/sass/dart-sass/releases/tag/1.26.0

**Comment by mrzapp** [comment]
Dang, introducing breaking changes in a minor version update. That's goddamn stupid :D

You can still run SASS globally in the meantime, but locking it it a good idea. Could you push that to v1.4?

**Comment by silend** [comment]
Oh yes, I can :)

**Comment by mrzapp** [comment]
Recent SASS will work in 1.4
